name: Build PHP Images Alpine

on:
  push:
    branches: [ main ]

  workflow_dispatch:

  schedule:
    - cron: '0 18 * * 6'

jobs:
  build_and_push_php70:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Ali
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: Build and push 7.0-cli-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.0-cli
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.0-cli-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.0-cli-alpine

      - name: Build and push 7.0-fpm-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.0-fpm
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.0-fpm-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.0-fpm-alpine

  build_and_push_php71:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Ali
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: Build and push 7.1-cli-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.1-cli
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.1-cli-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.1-cli-alpine

      - name: Build and push 7.1-fpm-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.1-fpm
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.1-fpm-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.1-fpm-alpine

  build_and_push_php72:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Ali
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: Build and push 7.2-cli-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.2-cli
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.2-cli-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.2-cli-alpine

      - name: Build and push 7.2-fpm-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.2-fpm
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.2-fpm-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.2-fpm-alpine

  build_and_push_php73:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Ali
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: Build and push 7.3-cli-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.3-cli
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.3-cli-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.3-cli-alpine

      - name: Build and push 7.3-fpm-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.3-fpm
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.3-fpm-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.3-fpm-alpine

  build_and_push_php74:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Ali
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: Build and push 7.4-cli-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.4-cli
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.4-cli-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.4-cli-alpine

      - name: Build and push 7.4-fpm-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./7.4-fpm
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:7.4-fpm-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:7.4-fpm-alpine

  build_and_push_php80:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Ali
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: Build and push 8.0-cli-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./8.0-cli
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:8.0-cli-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:8.0-cli-alpine

      - name: Build and push 8.0-fpm-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./8.0-fpm
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:8.0-fpm-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:8.0-fpm-alpine

  build_and_push_php81:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Ali
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ALI_DOCKER_REPO }}
          username: ${{ secrets.ALI_DOCKER_USER }}
          password: ${{ secrets.ALI_DOCKER_PASS }}

      - name: Build and push 8.1-cli-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./8.1-cli
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:8.1-cli-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:8.1-cli-alpine

      - name: Build and push 8.1-fpm-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./8.1-fpm
          file: Dockerfile-alpine
          push: true
          tags: |
            suyar/php:8.1-fpm-alpine
            ${{ secrets.ALI_DOCKER_REPO }}/suyar/php:8.1-fpm-alpine
